---
sidebar: sidebar 
permalink: concept-storage-fleets.html 
keywords: storage fleets, fleet management, storage organization, folders, ONTAP, clusters, storage systems, resource grouping, delegated administration, fleet design, netapp console local 
summary: 儲存設備機組用於將您在 NetApp Console 本機部署中一起管理的儲存設備系統分組。使用資料夾對相關的機組進行分組。您可以在所需範圍內套用原則、授予存取權限並監控健全狀況。 
---
= 了解 NetApp Console 本地部署中的儲存設備機組
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
儲存設備機組用於將您在 NetApp Console 本機部署中一起管理的儲存設備系統分組。使用資料夾對相關的機組進行分組。您可以在所需範圍內套用原則、授予存取權限並監控健全狀況。



[[why-fleets-matter]]
== 機組為何重要

隨著儲存設備環境的擴展，以隔離方式管理各個叢集變得不再可行。機組提供了一種結構化的方式，將相關的儲存設備系統分組，以便您可以將其作為一個整體進行操作。您無需逐個叢集設定原則或存取控制，只需在機組層級套用一次即可。這減少了重複的管理工作，並確保機組中的每個叢集都依照相同的標準運作。



[[how-folders-and-fleets-organize-your-resources]]
== 資料夾和機組如何組織您的資源

貴組織的資源層級結構由資料夾和機組組成。資料夾將相關的機組分組，機組將儲存設備系統分組。

* *組織*是層級結構中的最高層級，代表您的公司。
* *資料夾*有助於您組織相關的機組。例如，您可以為每個區域或業務單位建立一個資料夾，然後在每個資料夾內建立機組。資料夾可以包含其他資料夾或機組，但不能直接關聯儲存設備系統。當您在資料夾層級為成員指派角色時，該成員將繼承該角色，並適用於資料夾內的所有機組。
* *機組* 將您管理的儲存設備系統分組在一起。您可以將儲存設備系統與機組建立關聯，並將成員指派至機組以授予其存取權限。



NOTE: 資料夾是一種組織工具，對於沒有 IAM 權限（例如組織管理員、資料夾管理員或機組管理員角色）的成員而言不可見。成員存取機組，而不是資料夾。



[[fleet-examples]]
== 機組範例

機組的組織方式取決於您的營運模式。常見方法包括：

* *按環境劃分* 為生產、開發和測試工作負載建立分隔的機組。這樣可以確保生產環境的儲存設備受到更嚴格的效能和容量原則約束，同時為較低配置的環境提供更大的靈活度。
* *按業務單位* 將服務於特定部門（例如財務、工程或人力資源）的叢集分組到專用機組中。然後，您可以將儲存管理職責指派給該業務單位內的團隊成員，而不會將其他機組暴露給他們。
* *按位置或資料中心* 當叢集分佈在各個站台時，按位置進行組織可監控站台層級的健全狀況、套用特定區域的分層原則，並追蹤每個站台的容量消耗。
* *按應用程式層* 將主機特定類型工作負載（資料庫、檔案共用或虛擬機器）的叢集分組，以便您可以將針對該工作負載效能概況調整的儲存設備類別套用至整個機組。



TIP: 使用資料夾來新增另一個組織層級。例如，為每個區域建立一個資料夾，然後在每個區域資料夾中建立以環境為基礎的機組。



[[how-fleets-connect-to-storage-classes]]
== 機組如何連接到儲存設備類別

將儲存設備類別與機組關聯後，Console 本機部署會將該類別中的原則套用至機組內的所有儲存資源配置。在機組內佈建的工作負載會自動繼承儲存設備類別中定義的效能、容量和分層規則，而無需管理員在佈建時選擇或驗證原則設定。這使得機組成為在服務於相同目的的叢集中強制執行一致儲存行為的主要方式。



[[how-folders-and-fleets-support-access-control-and-visibility]]
== 資料夾和機組如何支援存取控制和可見度

資料夾和機組作為使用者存取的邊界：

* 在*資料夾*層級指派角色時，成員將繼承該角色，並擁有該資料夾內所有機組和資源的存取權限。這使得組織管理員可以透過建立資料夾並指派資料夾或機組管理員角色來委派管理職責。這些管理員隨後可以管理其資料夾內的所有機組，而無需存取整個組織。
* 當您在 *機組* 層級指派角色時，該成員只能存取該機組內的儲存設備系統。


這樣，您可以將儲存管理委派給團隊成員或應用程式擁有者，而無需讓他們看到基礎架構中不相關的部分。Console 本機部署提供機組層級的健全狀況和效能監控，讓您可以從單一檢視查看機組中所有叢集的狀態、及早發現問題，並在問題影響工作負載之前採取行動。
