---
sidebar: sidebar 
permalink: concept-storage-class-policies.html 
keywords: storage class policies, policies, storage class, IOPS, latency, throughput, capacity, security, data protection, performance policy, tiering, encryption, ransomware protection, storage standardization, policy enforcement, compliance monitoring, netapp console local 
summary: 了解作為 NetApp Console 本機部署中儲存設備類別建置模組的原則。 
---
= 了解 NetApp Console 本機部署中的儲存設備類別原則
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
儲存類別原則是建立儲存設備類別的基本組成部分。每個原則控制儲存設備行為的特定方面。將原則組合成儲存設備類別時，即可建立可重複使用的範本，NetApp Console 本機部署會在資源配置時自動強制執行該範本，並在工作負載的整個生命週期內持續監控。



[[policies-as-building-blocks]]
== 原則作為建構區塊

儲存設備類別由一個或多個原則組成，每個原則控制儲存設備行為的不同面向。儲存管理員定義原則來編碼企業標準（效能預期、容量閾值和資料放置規則），然後將這些原則組合成儲存設備類別範本。當使用儲存設備類別進行工作負載資源配置時，它將繼承該類別中的所有原則。這種設計將定義標準的責任與資源配置行為分隔，因此可以透過自動化工作流程以一致的方式配置儲存設備，而無需進行個別的組態決策。



[[types-of-storage-class-policies]]
== 儲存設備類別原則的類型

NetApp Console 本機部署包含四種類型的原則，可用於建置儲存設備類別：

效能原則:: 效能原則為工作負載設定預期 IOPS/TB、峰值 IOPS/TB、絕對最小 IOPS 和預期延遲目標。NetApp Console 本機部署使用這些值，在資源配置時建議具有足夠餘裕的叢集，並在資源配置後偵測 IOPS 或延遲偏移。
容量原則:: 容量原則可控制 Volume 消耗與管理空間的方式。它會設定保留空間（Thick、Thin 或系統預設值）、自動成長行為、FabricPool 分層，以及是否要將 NAS 工作負載資源配置為 FlexVol® 或 FlexGroup Volume。
安全性原則:: 安全性原則為工作負載設定加密、勒索軟體保護和 FIPS 要求。每個屬性都可以設定為必填值，也可以保留為「any」以接受系統預設值。
資料保護原則:: 資料保護原則設定每個時間間隔內保留的快照數量，以確保使用該原則的工作負載獲得一致的備份計畫。




[[default-policies]]
== 預設原則

Console 本機部署包含所有四種原則類型的系統定義原則。建立儲存設備類別時，您可以直接使用這些原則，也可以將其複本作為起點，以建立符合組織需求的自訂原則。



[[performance-policies]]
=== 效能原則

[cols="2,1,1,1,1,1,3"]
|===
| Name | 類型 | 預期 IOPS/TB | 峰值 IOPS/TB | 絕對最小 IOPS | 預期延遲（毫秒） | 總結 


| 資料庫資料的 Extreme | 系統定義 | 12,288 | 24,576 | 2,000 | 1 | 適用於需要持續高 IOPS 和亞毫秒延遲的交易項目資料庫資料 Volume。 


| 資料庫日誌的 Extreme | 系統定義 | 22,528 | 45,056 | 4,000 | 1 | 適用於需要最高 IOPS 下限的資料庫交易記錄 Volume，以防止寫入瓶頸。 


| Extreme for Database Shared Data | 系統定義 | 16,384 | 32,768 | 2,000 | 1 | 適用於多個主機存取的共享資料庫 Volume，需要高處理量和一致的延遲。 


| 極致效能 | 系統定義 | 6,144 | 12,288 | 1,000 | 1 | 適用於需要高突發 IOPS 和可預測低延遲的 HPC、AI/ML 和分析工作負載。 


| 效能 | 系統定義 | 2,048 | 4,096 | 500 | 2 | 適用於需要可靠效能但無極端 IOPS 需求的虛擬化及企業應用程式。 


| 價值 | 系統定義 | 128 | 512 | 75 | 17 | 適用於對成本敏感的工作負載，例如使用者主目錄、檔案共用和存檔。 
|===


[[capacity-policies]]
=== 容量原則

[cols="2,1,1,1,1,1,3"]
|===
| Name | 類型 | 保留空間 | 自動擴充模式 | 分層原則 | Volume 類型（NAS） | 總結 


| 預設 | 系統定義 | 系統預設設定 | 系統預設設定 | 無 | 系統預設設定 | 適用於平台預設容量行為可接受的一般工作負載。 


| 生產 | 系統定義 | 系統預設設定 | 擴充 | 無 | 系統預設設定 | 適用於必須自動擴充以防止空間不足故障的生產工作負載。 
|===


[[security-policies]]
=== 安全性原則

[cols="2,1,1,1,1,3"]
|===
| Name | 類型 | 加密 | 勒索軟體防護 | FIPS | 總結 


| 預設 | 系統定義 | 任何 | 任何 | 任何 | 適用於平台預設安全性行為可以接受的工作負載。 


| 反勒索軟體 | 系統定義 | 任何 | 在 | 任何 | 適用於包含敏感或業務關鍵資料且需要作用中勒索軟體保護的工作負載。 


| 生產 | 系統定義 | 已啟用 | 任何 | 任何 | 適用於需要加密以符合法規的生產工作負載。 
|===


[[data-protection-policies]]
=== 資料保護原則

[cols="2,1,1,1,1,1,3"]
|===
| Name | 類型 | 每小時快照 | 每日快照 | 每週快照 | 每月快照 | 總結 


| 預設 | 系統定義 | 6 | 2 | 2 | 0 | 適用於需要短期恢復點而不需要長期保留例行成本的標準工作負載。 


| 3 個月（每小時） | 系統定義 | 23 | 6 | 4 | 3 | 適用於需要精細的日內恢復點和三個月歷史資料保留的受監管或業務關鍵型工作負載。 
|===