---
sidebar: sidebar 
permalink: task-get-help.html 
keywords: help, ticket, open support case, support, netapp support, technical support, call support, phone number, open ticket, web ticket, open an issue 
summary: 'NetApp 以多種方式為 NetApp Console 本地部署提供支援。豐富的免費自助支援選項全年無休均可使用，例如知識庫 (KB) 文章和社群論壇。您的支援註冊包含透過線上工單系統提供的遠端技術支援。' 
---
= 取得 NetApp Console 本機部署的協助
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp 以多種方式為 NetApp Console 本機部署提供支援。豐富的免費自助支援選項全天候 （24x7） 可用，例如知識庫 （KB） 文章和社群論壇。您可以使用與 NetApp Console 本機部署相關聯的任何儲存資源的序號來註冊支援。註冊後，您可以透過線上工單系統獲得遠端技術支援。



[[use-self-support-options]]
== 使用自助選項

這些選項全天候 24 小時、每週 7 天免費提供：

* 文件
+
您目前正在檢視的 NetApp Console 本機部署文件。

* https://kb.netapp.com/Cloud/BlueXP["知識庫"^]
+
搜尋 NetApp 知識庫的文章，協助您疑難排解問題。





[[open-a-support-case-with-netapp-console-local-deployment]]
== 使用 NetApp Console 本機部署開啟支援案例

使用透過您的 NetApp Console 本機部署環境代管的其中一個 NetApp 儲存系統序號，開立支援案例。

.步驟
. 請前往 https://mysupport.netapp.com["NetApp 支援網站"^]並使用您的 NetApp 支援憑證登入。
. 選擇 *Cases and Parts > Create Technical Case*。
. 輸入與發生該問題的 Console 本機部署產品相關聯的 NetApp 儲存系統序號。
. 建立新的支援案例，並為 NetApp Console 本地部署選擇適當的類別代碼。




[[download-a-support-bundle]]
== 下載支援套裝組合

支援套裝組合包含最新的日誌和組態資訊。您可以下載最新的套裝組合，並在需要時將其傳送給 NetApp 技術支援。

.步驟
. 選擇 *Administration > Support* 以檢視支援頁面。
. 在「支援」卡上，選擇 *建立* 以建立日誌和組態資料的套裝組合。
. 建立套裝組合後，選擇「下載」。系統會提示您下載 ZIP 檔案。
+
系統一次只能保存一個套裝組合。建立新的支援套裝組合會替換先前的套裝組合。


