---
sidebar: sidebar 
permalink: task-analyzer-volume-latency-investigate.html 
keywords: latency, slow performance, delay center, workload analyzer, investigate, netapp console 
summary: 使用工作負載分析器調查 Volume 上的延遲，以確定 I/O 路徑的哪個部分導致回應時間緩慢。 
---
= 調查 NetApp Console 本機部署中 Volume 的高延遲
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在 NetApp Console 本機部署中使用 Workload Analyzer 來尋找 Volume 回應時間慢的來源。

如果從警示或 Volume 清單中開啟分析器，則 Volume 已被選取，您可以專注於時間範圍和圖表細分。

當應用程式效能下降時，請確認是 I/O 路徑中的哪個部分導致效能降低。延遲分析區段會依延遲中心細分回應時間，讓您能夠區分網路問題、資料處理例行成本、彙總爭用及其他影響因素。

.步驟
. 使用下列方法之一開啟工作負載分析器：
+
** 從 *健全狀況* 功能表中，選擇 *工作負載分析器*，然後在 *Volume* 欄位中搜尋並選擇要調查的 Volume。
** 從「儲存設備 > 機組 > 清單」頁面，導覽至要分析的 Volume，然後從行動選單中選擇「分析」。
** 在「警報 > 概覽」頁面中，選擇要調查的 Volume 的容量相關警報，然後從警報詳細資料中選擇「分析」。


. 將*時間範圍*設定為涵蓋效能問題發生的時間段，然後選擇*分析*。
. 請審查「事件時間軸」部分，以了解與延遲增加相符的組態變更和警示。
+
分析器將組態變更事件（扳手圖示）和警報事件（警告和關鍵圖示）繪製在與延遲圖相同的時間軸上，因此可以輕鬆查看變更是否先於效能下降。

. 在「延遲」部分，開啟「檢視」下拉選單，然後選擇「按延遲中心細分」。圖表顯示每個延遲中心對總延遲隨時間變化的貢獻。延遲中心包括：
+
** 讀取延遲
** 寫入延遲
** 其他延遲


. 將滑鼠懸停在圖表上延遲最高的點上，即可查看每個延遲中心的值及其佔總延遲的百分比。
+
最大的延遲中心通常指向爭用資源。當共享的資源無法滿足需求時，使用該資源的 Volume 需要等待更長時間才能完成 I/O 作業。降低該資源的負載，例如遷移工作負載或調整 QoS 限制，可以降低延遲。

. 找出主要貢獻者，並利用其數值來確定後續步驟：
+
** 高讀取延遲可能表示磁碟爭用。請查看「資源使用率」部分以確認彙總繁忙百分比。
** 高寫入延遲可能表示 NIC 飽和或叢集外部的網路路徑有問題。
** *其他延遲*過高可能表示即時效率設定消耗的 CPU 資源超過了工作負載所能承受的範圍。請考慮調整效率設定或 QoS。
** 高雲端延遲可能表示工作負載頻繁存取容量分層上的冷資料。請考慮調整分層原則。


. 如果延遲中心無法說明速度下降的原因，請查看「容量分析」部分。當 ONTAP 系統使用率超過 85% 時，無論延遲中心的細分情況如何，高使用率都可能導致效能問題。
. 如果延遲在變更事件發生後立即增加，請結合事件詳細資料和相關圖表來驗證可能的原因：
+
** 對於 QoS 變更，請將延遲線與 QoS 限制線進行比較，並審查處理量圖表，以了解需求是否達到原則上限。
** 對於彙總或 Volume 移動，請將延遲峰值與同一時間段內顯示的節點和彙總使用率值進行比較。
** 對於分層原則變更，請審查雲端延遲貢獻，以確定變更後冷資料存取是否增加。




.完成後
如果組態或放置問題導致了該問題，且 Console 本機部署可以解決該問題，則 Volume 上的警報可能會提供 Fix-It 選項。

link:reference-workload-analyzer-metrics.html["了解 NetApp Console 本機部署中的工作負載分析器計量"]。
